// Code generated by protoc-gen-go. DO NOT EDIT.
// source: deployment-service.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ServerMode int32

const (
	ServerMode_Development ServerMode = 0
	ServerMode_Production  ServerMode = 1
)

var ServerMode_name = map[int32]string{
	0: "Development",
	1: "Production",
}

var ServerMode_value = map[string]int32{
	"Development": 0,
	"Production":  1,
}

func (x ServerMode) String() string {
	return proto.EnumName(ServerMode_name, int32(x))
}

func (ServerMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_210f234a7064ba9a, []int{0}
}

type Action int32

const (
	Action_Created    Action = 0
	Action_Removed    Action = 1
	Action_Updated    Action = 2
	Action_Recreated  Action = 3
	Action_NotChanged Action = 4
)

var Action_name = map[int32]string{
	0: "Created",
	1: "Removed",
	2: "Updated",
	3: "Recreated",
	4: "NotChanged",
}

var Action_value = map[string]int32{
	"Created":    0,
	"Removed":    1,
	"Updated":    2,
	"Recreated":  3,
	"NotChanged": 4,
}

func (x Action) String() string {
	return proto.EnumName(Action_name, int32(x))
}

func (Action) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_210f234a7064ba9a, []int{1}
}

type Request struct {
	Path                 string     `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Mode                 ServerMode `protobuf:"varint,2,opt,name=mode,proto3,enum=api.ServerMode" json:"mode,omitempty"`
	Recreate             bool       `protobuf:"varint,3,opt,name=recreate,proto3" json:"recreate,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_210f234a7064ba9a, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Request) GetMode() ServerMode {
	if m != nil {
		return m.Mode
	}
	return ServerMode_Development
}

func (m *Request) GetRecreate() bool {
	if m != nil {
		return m.Recreate
	}
	return false
}

type ReleaseInfo struct {
	ImageTag             string   `protobuf:"bytes,1,opt,name=image_tag,json=imageTag,proto3" json:"image_tag,omitempty"`
	ReleaseDate          string   `protobuf:"bytes,2,opt,name=release_date,json=releaseDate,proto3" json:"release_date,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReleaseInfo) Reset()         { *m = ReleaseInfo{} }
func (m *ReleaseInfo) String() string { return proto.CompactTextString(m) }
func (*ReleaseInfo) ProtoMessage()    {}
func (*ReleaseInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_210f234a7064ba9a, []int{1}
}

func (m *ReleaseInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReleaseInfo.Unmarshal(m, b)
}
func (m *ReleaseInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReleaseInfo.Marshal(b, m, deterministic)
}
func (m *ReleaseInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReleaseInfo.Merge(m, src)
}
func (m *ReleaseInfo) XXX_Size() int {
	return xxx_messageInfo_ReleaseInfo.Size(m)
}
func (m *ReleaseInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ReleaseInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ReleaseInfo proto.InternalMessageInfo

func (m *ReleaseInfo) GetImageTag() string {
	if m != nil {
		return m.ImageTag
	}
	return ""
}

func (m *ReleaseInfo) GetReleaseDate() string {
	if m != nil {
		return m.ReleaseDate
	}
	return ""
}

type ServiceID struct {
	Group                string   `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Package              string   `protobuf:"bytes,2,opt,name=package,proto3" json:"package,omitempty"`
	Kind                 string   `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceID) Reset()         { *m = ServiceID{} }
func (m *ServiceID) String() string { return proto.CompactTextString(m) }
func (*ServiceID) ProtoMessage()    {}
func (*ServiceID) Descriptor() ([]byte, []int) {
	return fileDescriptor_210f234a7064ba9a, []int{2}
}

func (m *ServiceID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceID.Unmarshal(m, b)
}
func (m *ServiceID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceID.Marshal(b, m, deterministic)
}
func (m *ServiceID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceID.Merge(m, src)
}
func (m *ServiceID) XXX_Size() int {
	return xxx_messageInfo_ServiceID.Size(m)
}
func (m *ServiceID) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceID.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceID proto.InternalMessageInfo

func (m *ServiceID) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

func (m *ServiceID) GetPackage() string {
	if m != nil {
		return m.Package
	}
	return ""
}

func (m *ServiceID) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

type ServiceInfo struct {
	Path      string       `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Provider  string       `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	ServiceId *ServiceID   `protobuf:"bytes,3,opt,name=serviceId,proto3" json:"serviceId,omitempty"`
	Release   *ReleaseInfo `protobuf:"bytes,4,opt,name=release,proto3" json:"release,omitempty"`
	// Types that are valid to be assigned to ActionVariants:
	//	*ServiceInfo_Action
	//	*ServiceInfo_ErrorDescription
	ActionVariants       isServiceInfo_ActionVariants `protobuf_oneof:"action_variants"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *ServiceInfo) Reset()         { *m = ServiceInfo{} }
func (m *ServiceInfo) String() string { return proto.CompactTextString(m) }
func (*ServiceInfo) ProtoMessage()    {}
func (*ServiceInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_210f234a7064ba9a, []int{3}
}

func (m *ServiceInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceInfo.Unmarshal(m, b)
}
func (m *ServiceInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceInfo.Marshal(b, m, deterministic)
}
func (m *ServiceInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceInfo.Merge(m, src)
}
func (m *ServiceInfo) XXX_Size() int {
	return xxx_messageInfo_ServiceInfo.Size(m)
}
func (m *ServiceInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceInfo proto.InternalMessageInfo

func (m *ServiceInfo) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *ServiceInfo) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

func (m *ServiceInfo) GetServiceId() *ServiceID {
	if m != nil {
		return m.ServiceId
	}
	return nil
}

func (m *ServiceInfo) GetRelease() *ReleaseInfo {
	if m != nil {
		return m.Release
	}
	return nil
}

type isServiceInfo_ActionVariants interface {
	isServiceInfo_ActionVariants()
}

type ServiceInfo_Action struct {
	Action Action `protobuf:"varint,5,opt,name=action,proto3,enum=api.Action,oneof"`
}

type ServiceInfo_ErrorDescription struct {
	ErrorDescription string `protobuf:"bytes,6,opt,name=error_description,json=errorDescription,proto3,oneof"`
}

func (*ServiceInfo_Action) isServiceInfo_ActionVariants() {}

func (*ServiceInfo_ErrorDescription) isServiceInfo_ActionVariants() {}

func (m *ServiceInfo) GetActionVariants() isServiceInfo_ActionVariants {
	if m != nil {
		return m.ActionVariants
	}
	return nil
}

func (m *ServiceInfo) GetAction() Action {
	if x, ok := m.GetActionVariants().(*ServiceInfo_Action); ok {
		return x.Action
	}
	return Action_Created
}

func (m *ServiceInfo) GetErrorDescription() string {
	if x, ok := m.GetActionVariants().(*ServiceInfo_ErrorDescription); ok {
		return x.ErrorDescription
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ServiceInfo) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ServiceInfo_Action)(nil),
		(*ServiceInfo_ErrorDescription)(nil),
	}
}

type ServicesResponse struct {
	Services             []*ServiceInfo `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ServicesResponse) Reset()         { *m = ServicesResponse{} }
func (m *ServicesResponse) String() string { return proto.CompactTextString(m) }
func (*ServicesResponse) ProtoMessage()    {}
func (*ServicesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_210f234a7064ba9a, []int{4}
}

func (m *ServicesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServicesResponse.Unmarshal(m, b)
}
func (m *ServicesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServicesResponse.Marshal(b, m, deterministic)
}
func (m *ServicesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServicesResponse.Merge(m, src)
}
func (m *ServicesResponse) XXX_Size() int {
	return xxx_messageInfo_ServicesResponse.Size(m)
}
func (m *ServicesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ServicesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ServicesResponse proto.InternalMessageInfo

func (m *ServicesResponse) GetServices() []*ServiceInfo {
	if m != nil {
		return m.Services
	}
	return nil
}

type Response struct {
	// Types that are valid to be assigned to ResponseVariants:
	//	*Response_ServicesResponse
	//	*Response_ErrorDescription
	ResponseVariants     isResponse_ResponseVariants `protobuf_oneof:"response_variants"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_210f234a7064ba9a, []int{5}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

type isResponse_ResponseVariants interface {
	isResponse_ResponseVariants()
}

type Response_ServicesResponse struct {
	ServicesResponse *ServicesResponse `protobuf:"bytes,1,opt,name=services_response,json=servicesResponse,proto3,oneof"`
}

type Response_ErrorDescription struct {
	ErrorDescription string `protobuf:"bytes,2,opt,name=error_description,json=errorDescription,proto3,oneof"`
}

func (*Response_ServicesResponse) isResponse_ResponseVariants() {}

func (*Response_ErrorDescription) isResponse_ResponseVariants() {}

func (m *Response) GetResponseVariants() isResponse_ResponseVariants {
	if m != nil {
		return m.ResponseVariants
	}
	return nil
}

func (m *Response) GetServicesResponse() *ServicesResponse {
	if x, ok := m.GetResponseVariants().(*Response_ServicesResponse); ok {
		return x.ServicesResponse
	}
	return nil
}

func (m *Response) GetErrorDescription() string {
	if x, ok := m.GetResponseVariants().(*Response_ErrorDescription); ok {
		return x.ErrorDescription
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Response) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Response_ServicesResponse)(nil),
		(*Response_ErrorDescription)(nil),
	}
}

func init() {
	proto.RegisterEnum("api.ServerMode", ServerMode_name, ServerMode_value)
	proto.RegisterEnum("api.Action", Action_name, Action_value)
	proto.RegisterType((*Request)(nil), "api.Request")
	proto.RegisterType((*ReleaseInfo)(nil), "api.ReleaseInfo")
	proto.RegisterType((*ServiceID)(nil), "api.ServiceID")
	proto.RegisterType((*ServiceInfo)(nil), "api.ServiceInfo")
	proto.RegisterType((*ServicesResponse)(nil), "api.ServicesResponse")
	proto.RegisterType((*Response)(nil), "api.Response")
}

func init() {
	proto.RegisterFile("deployment-service.proto", fileDescriptor_210f234a7064ba9a)
}

var fileDescriptor_210f234a7064ba9a = []byte{
	// 519 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x53, 0x41, 0x6f, 0xd3, 0x30,
	0x14, 0x6e, 0xda, 0xae, 0x4d, 0x5e, 0xb6, 0x36, 0x35, 0x20, 0x45, 0xe5, 0x52, 0x82, 0x10, 0x55,
	0xb5, 0xf6, 0x50, 0xc4, 0x1d, 0x58, 0x0e, 0xeb, 0x61, 0x03, 0x79, 0x70, 0xa5, 0x32, 0xf1, 0x23,
	0x8b, 0xd6, 0xc6, 0xc6, 0x49, 0x23, 0x71, 0xe3, 0x47, 0xf0, 0x83, 0x91, 0x1d, 0x27, 0xad, 0xd0,
	0x76, 0xcb, 0xf7, 0xde, 0xe7, 0xcf, 0xdf, 0xfb, 0xe2, 0x07, 0x21, 0x47, 0xb9, 0x13, 0xbf, 0xf7,
	0x98, 0x97, 0xcb, 0x02, 0x55, 0x95, 0x25, 0xb8, 0x92, 0x4a, 0x94, 0x82, 0xf4, 0x98, 0xcc, 0xa2,
	0xef, 0x30, 0xa4, 0xf8, 0xeb, 0x80, 0x45, 0x49, 0x08, 0xf4, 0x25, 0x2b, 0xef, 0x43, 0x67, 0xe6,
	0xcc, 0x3d, 0x6a, 0xbe, 0xc9, 0x6b, 0xe8, 0xef, 0x05, 0xc7, 0xb0, 0x3b, 0x73, 0xe6, 0xa3, 0xf5,
	0x78, 0xc5, 0x64, 0xb6, 0xba, 0x43, 0x55, 0xa1, 0xba, 0x11, 0x1c, 0xa9, 0x69, 0x92, 0x29, 0xb8,
	0x0a, 0x13, 0x85, 0xac, 0xc4, 0xb0, 0x37, 0x73, 0xe6, 0x2e, 0x6d, 0x71, 0x74, 0x03, 0x3e, 0xc5,
	0x1d, 0xb2, 0x02, 0x37, 0xf9, 0x4f, 0x41, 0x5e, 0x82, 0x97, 0xed, 0x59, 0x8a, 0xdb, 0x92, 0xa5,
	0xf6, 0x22, 0xd7, 0x14, 0xbe, 0xb2, 0x94, 0xbc, 0x82, 0x73, 0x55, 0x73, 0xb7, 0x5c, 0x6b, 0x75,
	0x4d, 0xdf, 0xb7, 0xb5, 0x58, 0xcb, 0x7d, 0x06, 0xef, 0xae, 0x1e, 0x62, 0x13, 0x93, 0xe7, 0x70,
	0x96, 0x2a, 0x71, 0x90, 0x56, 0xa8, 0x06, 0x24, 0x84, 0xa1, 0x64, 0xc9, 0x03, 0x4b, 0x1b, 0x81,
	0x06, 0xea, 0x01, 0x1f, 0xb2, 0x9c, 0x1b, 0x8f, 0x1e, 0x35, 0xdf, 0xd1, 0x9f, 0x2e, 0xf8, 0x8d,
	0xa2, 0x36, 0xf8, 0x58, 0x08, 0x53, 0x70, 0xa5, 0x12, 0x55, 0xc6, 0x51, 0x59, 0xc9, 0x16, 0x93,
	0x4b, 0xf0, 0x6c, 0xaa, 0x9b, 0x5a, 0xd8, 0x5f, 0x8f, 0xda, 0x94, 0x8c, 0x4d, 0x7a, 0x24, 0x90,
	0x05, 0x0c, 0xed, 0x34, 0x61, 0xdf, 0x70, 0x03, 0xc3, 0x3d, 0x49, 0x88, 0x36, 0x04, 0xf2, 0x06,
	0x06, 0x2c, 0x29, 0x33, 0x91, 0x87, 0x67, 0x26, 0x7c, 0xdf, 0x50, 0x3f, 0x9a, 0xd2, 0x75, 0x87,
	0xda, 0x26, 0x59, 0xc2, 0x04, 0x95, 0x12, 0x6a, 0xcb, 0xb1, 0x48, 0x54, 0x26, 0xcd, 0x89, 0x81,
	0x76, 0x79, 0xdd, 0xa1, 0x81, 0x69, 0xc5, 0xc7, 0xce, 0xa7, 0x09, 0x8c, 0xeb, 0x83, 0xdb, 0x8a,
	0xa9, 0x8c, 0xe5, 0x65, 0x11, 0x7d, 0x80, 0xc0, 0x9a, 0x2d, 0x28, 0x16, 0x52, 0xe4, 0x05, 0x92,
	0x4b, 0x70, 0xad, 0xeb, 0x22, 0x74, 0x66, 0xbd, 0xd6, 0xe9, 0x49, 0x54, 0xb4, 0x65, 0x44, 0x7f,
	0x1d, 0x70, 0xdb, 0xa3, 0x31, 0x4c, 0x9a, 0xc6, 0x56, 0xd9, 0xa2, 0x89, 0xd3, 0x5f, 0xbf, 0x38,
	0xd5, 0x68, 0x2f, 0xd3, 0x3e, 0x8b, 0xff, 0x0d, 0x3c, 0x3a, 0x56, 0xf7, 0xc9, 0xb1, 0x9e, 0xc1,
	0xa4, 0xb9, 0xab, 0x1d, 0x6c, 0xb1, 0x04, 0x38, 0xbe, 0x55, 0x32, 0x06, 0x3f, 0xc6, 0x0a, 0x77,
	0x42, 0xea, 0x5d, 0x08, 0x3a, 0x64, 0x04, 0xf0, 0x45, 0x09, 0x7e, 0x30, 0x71, 0x04, 0xce, 0xe2,
	0x16, 0x06, 0x75, 0xba, 0xc4, 0x87, 0xe1, 0x95, 0x79, 0xbe, 0x3c, 0xe8, 0x68, 0x40, 0x71, 0x2f,
	0x2a, 0xe4, 0x81, 0xa3, 0xc1, 0x37, 0xc9, 0x4d, 0xa7, 0x4b, 0x2e, 0xc0, 0xa3, 0xf6, 0x9d, 0xf3,
	0xa0, 0xa7, 0xf5, 0x6e, 0x45, 0x79, 0x75, 0xcf, 0xf2, 0x14, 0x79, 0xd0, 0x5f, 0xbf, 0x07, 0x88,
	0xdb, 0xdd, 0x23, 0x6f, 0x61, 0x50, 0x23, 0x72, 0x6e, 0xff, 0xb9, 0xd9, 0xba, 0xe9, 0x85, 0x45,
	0xb5, 0xf9, 0xa8, 0xf3, 0x63, 0x60, 0xb6, 0xf3, 0xdd, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x81,
	0x21, 0xfb, 0x9f, 0xb9, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DeploymentClient is the client API for Deployment service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DeploymentClient interface {
	Deploy(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type deploymentClient struct {
	cc grpc.ClientConnInterface
}

func NewDeploymentClient(cc grpc.ClientConnInterface) DeploymentClient {
	return &deploymentClient{cc}
}

func (c *deploymentClient) Deploy(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/api.Deployment/Deploy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeploymentServer is the server API for Deployment service.
type DeploymentServer interface {
	Deploy(context.Context, *Request) (*Response, error)
}

// UnimplementedDeploymentServer can be embedded to have forward compatible implementations.
type UnimplementedDeploymentServer struct {
}

func (*UnimplementedDeploymentServer) Deploy(ctx context.Context, req *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Deploy not implemented")
}

func RegisterDeploymentServer(s *grpc.Server, srv DeploymentServer) {
	s.RegisterService(&_Deployment_serviceDesc, srv)
}

func _Deployment_Deploy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeploymentServer).Deploy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Deployment/Deploy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeploymentServer).Deploy(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _Deployment_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Deployment",
	HandlerType: (*DeploymentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Deploy",
			Handler:    _Deployment_Deploy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "deployment-service.proto",
}
